apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: favour-certificate
  namespace: sock-shop
spec:
  secretName: favour-secret
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: favouredsmiles.me
  dnsNames:
  - favouredsmiles.me
 